### ISSUE TITLE
networkx problem: cannot import name 'release'

### ISSUE THREAD

**Issue by modeSolver300** [datajoint/datajoint-python#192]
Hello,

I'm getting the following error when I try to import datajoint in the python console:

import datajoint
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Admin\Desktop\datajoint-python\datajoint\__init__.py", line 54, in <module>
    from .connection import conn, Connection
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Admin\Desktop\datajoint-python\datajoint\connection.py", line 11, in <module>
    from datajoint.erd import ERD
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Admin\Desktop\datajoint-python\datajoint\erd.py", line 8, in <module>
    import networkx as nx
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\networkx\__init__.py", line 43, in <module>
    from networkx import release
ImportError: cannot import name 'release'

Any advice you can provide would be much appreciated.

Thank you.

**Comment by fabiansinz** [comment]
Can you give us a bit more information on your operating system and the version of networkx that you are using (try `pip freeze` in the command line prompt)? Or 

```python
import networkx
print(networkx.__version__)
```

I assume you are using python3.4 or later, correct?

**Comment by modeSolver300** [comment]
Thanks for the response.  I'm using Windows 7, networkx version 1.11rc2 (I think this is the latest), and python 3.4.2.  I can't even run import networkx without the import name 'release' error.  I tried a reinstall, but no luck.

**Comment by fabiansinz** [comment]
Can you try 
```
pip3 install networkx==1.10
```
It may be that the release candidate version causes trouble.

**Comment by modeSolver300** [comment]
I moved back to version 1.9.1 of networkx and the problem is resolved.  Can you see any compatibility problems with version 1.9.1 and datajoint?  If so, I can also try version 1.10.

**Comment by fabiansinz** [comment]
No, at the moment I don't. If all tests run through (```nosetest3 tests/```) you should be good. Note, that we currently have a standing pull request that fixes a bug in the deletion of a restricted set of tuples. Maybe check back in a few days to see whether the pull request is accepted and update your version of datajoint.

**Comment by modeSolver300** [comment]
Thanks a lot for your help.

**Comment by fabiansinz** [comment]
You are most welcome.

**Comment by Holisticnature** [comment]
I ran into this error as well on Google Datalab very recently (Py 2.7). Installing to version 1.5 worked for me.
