### ISSUE TITLE
fetch fails to convert to numpy record array in joins

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#225]
In the unified pipeline, the following query results in error:
```python
In[1]: from pipeline import experiment
In[2]: (experiment.Session() * experiment.Scan()).fetch()

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-14e2199eaccf>", line 1, in <module>
    (experiment.Session() * experiment.Scan()).fetch()
  File "/Users/dimitri/dev/datajoint-python/datajoint/fetch.py", line 118, in __call__
    ret = np.array(ret, dtype=heading.as_dtype)
ValueError: invalid literal for int() with base 10: '2P3'
```

This seems to be specific to joins since querying each relation separately works fine:
```python
In[3]: experiment.Session().fetch()
```

This has to do with converting to numpy record array since `as_dict` works fine:
```python
In[4]: (experiment.Session() * experiment.Scan()).fetch(as_dict=True)
```

**Comment by dimitri-yatsenko** [comment]
Oh, i think i know what's going on there.  It's because the query uses `*` to specify the attributes and they come in a different order after join.  Bugfix coming up.
