### ISSUE TITLE
Provide a more informative error message when trying to set attributes in capital letters

### ISSUE THREAD

**Issue by ecobost** [datajoint/datajoint-python#299]
Minimal Example:
 ```python3
class Test(dj.Manual):
    definition="""
    index : int
    ---
    memory_in_Mb  : int # amount of memory to use
    """
```
Error in interactive view:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/datajoint/declare.py", line 162, in compile_attribute
    match = attribute_parser.parseString(line+'#', parseAll=True)
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1617, in parseString
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pyparsing.py", line 2394, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected ":" (at char 10), (line:1, col:11)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.5/dist-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/ipapp.py", line 353, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 381, in mainloop
    self.interact(display_banner=display_banner)
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 505, in interact
    self.run_cell(source_raw, store_history=True)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2902, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3006, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-487-ebd8008e55b6>", line 2, in <module>
    class Test(dj.Manual):
  File "/usr/local/lib/python3.5/dist-packages/datajoint/schema.py", line 154, in __call__
    self.process_relation_class(cls, context=self.context)
  File "/usr/local/lib/python3.5/dist-packages/datajoint/schema.py", line 134, in process_relation_class
    instance.declare()
  File "/usr/local/lib/python3.5/dist-packages/datajoint/base_relation.py", line 55, in declare
    declare(self.full_table_name, self.definition, self._context))
  File "/usr/local/lib/python3.5/dist-packages/datajoint/declare.py", line 135, in declare
    name, sql = compile_attribute(line, in_key)
  File "/usr/local/lib/python3.5/dist-packages/datajoint/declare.py", line 164, in compile_attribute
    logger.error('Declaration error in line: ', line)
Message: 'Declaration error in line: '
Arguments: ('memory_in_Mb  : int # amount of memory to use',)
---------------------------------------------------------------------------
ParseException                            Traceback (most recent call last)
<ipython-input-487-ebd8008e55b6> in <module>()
      1 @s
----> 2 class Test(dj.Manual):
      3     definition="""
      4     index : int
      5     ---

/usr/local/lib/python3.5/dist-packages/datajoint/schema.py in __call__(self, cls)
    152         if issubclass(cls, Part):
    153             raise DataJointError('The schema decorator should not be applied to Part relations')
--> 154         self.process_relation_class(cls, context=self.context)
    155         # Process part relations
    156         for part in cls._ordered_class_members:

/usr/local/lib/python3.5/dist-packages/datajoint/schema.py in process_relation_class(self, relation_class, context, assert_declared)
    132         if not instance.is_declared:
    133             assert not assert_declared, 'incorrect table name generation'
--> 134             instance.declare()
    135         if instance.is_declared and hasattr(instance, 'contents'):
    136             # process the contents attribute

/usr/local/lib/python3.5/dist-packages/datajoint/base_relation.py in declare(self)
     53         try:
     54             self.connection.query(
---> 55                 declare(self.full_table_name, self.definition, self._context))
     56         except pymysql.OperationalError as error:
     57             if error.args[0] == server_error_codes['command denied']:

/usr/local/lib/python3.5/dist-packages/datajoint/declare.py in declare(full_table_name, definition, context)
    133             index_sql.append(line)  # the SQL syntax is identical to DataJoint's
    134         else:
--> 135             name, sql = compile_attribute(line, in_key)
    136             if in_key and name not in primary_key:
    137                 primary_key.append(name)

/usr/local/lib/python3.5/dist-packages/datajoint/declare.py in compile_attribute(line, in_key)
    160 
    161     try:
--> 162         match = attribute_parser.parseString(line+'#', parseAll=True)
    163     except pp.ParseException:
    164         logger.error('Declaration error in line: ', line)

/usr/local/lib/python3.5/dist-packages/pyparsing.py in parseString(self, instring, parseAll)
   1615             else:
   1616                 # catch and re-raise exception from here, clears out pyparsing internal stack trace
-> 1617                 raise exc
   1618         else:
   1619             return tokens

/usr/local/lib/python3.5/dist-packages/pyparsing.py in parseString(self, instring, parseAll)
   1605             instring = instring.expandtabs()
   1606         try:
-> 1607             loc, tokens = self._parse( instring, 0 )
   1608             if parseAll:
   1609                 loc = self.preParse( instring, loc )

/usr/local/lib/python3.5/dist-packages/pyparsing.py in _parseCache(self, instring, loc, doActions, callPreParse)
   1512                 ParserElement.packrat_cache_stats[MISS] += 1
   1513                 try:
-> 1514                     value = self._parseNoCache(instring, loc, doActions, callPreParse)
   1515                 except ParseBaseException as pe:
   1516                     # cache a copy of the exception, without the traceback

/usr/local/lib/python3.5/dist-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1377             if self.mayIndexError or loc >= len(instring):
   1378                 try:
-> 1379                     loc,tokens = self.parseImpl( instring, preloc, doActions )
   1380                 except IndexError:
   1381                     raise ParseException( instring, len(instring), self.errmsg, self )

/usr/local/lib/python3.5/dist-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   3374                     raise ParseSyntaxException(instring, len(instring), self.errmsg, self)
   3375             else:
-> 3376                 loc, exprtokens = e._parse( instring, loc, doActions )
   3377             if exprtokens or exprtokens.haskeys():
   3378                 resultlist += exprtokens

/usr/local/lib/python3.5/dist-packages/pyparsing.py in _parseCache(self, instring, loc, doActions, callPreParse)
   1512                 ParserElement.packrat_cache_stats[MISS] += 1
   1513                 try:
-> 1514                     value = self._parseNoCache(instring, loc, doActions, callPreParse)
   1515                 except ParseBaseException as pe:
   1516                     # cache a copy of the exception, without the traceback

/usr/local/lib/python3.5/dist-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1381                     raise ParseException( instring, len(instring), self.errmsg, self )
   1382             else:
-> 1383                 loc,tokens = self.parseImpl( instring, preloc, doActions )
   1384 
   1385         tokens = self.postParse( instring, loc, tokens )

/usr/local/lib/python3.5/dist-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   3696     def parseImpl( self, instring, loc, doActions=True ):
   3697         if self.expr is not None:
-> 3698             return self.expr._parse( instring, loc, doActions, callPreParse=False )
   3699         else:
   3700             raise ParseException("",loc,self.errmsg,self)

/usr/local/lib/python3.5/dist-packages/pyparsing.py in _parseCache(self, instring, loc, doActions, callPreParse)
   1512                 ParserElement.packrat_cache_stats[MISS] += 1
   1513                 try:
-> 1514                     value = self._parseNoCache(instring, loc, doActions, callPreParse)
   1515                 except ParseBaseException as pe:
   1516                     # cache a copy of the exception, without the traceback

/usr/local/lib/python3.5/dist-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1381                     raise ParseException( instring, len(instring), self.errmsg, self )
   1382             else:
-> 1383                 loc,tokens = self.parseImpl( instring, preloc, doActions )
   1384 
   1385         tokens = self.postParse( instring, loc, tokens )

/usr/local/lib/python3.5/dist-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   2392             (self.matchLen==1 or instring.startswith(self.match,loc)) ):
   2393             return loc+self.matchLen, self.match
-> 2394         raise ParseException(instring, loc, self.errmsg, self)
   2395 _L = Literal
   2396 ParserElement._literalStringClass = Literal

ParseException: Expected ":" (at char 10), (line:1, col:11)

```

**Comment by dimitri-yatsenko** [comment]
We rely on the `pyparsing` library to parse the definitions and to display parsing errors.  Not sure how to get it to display more meaningful messages in general.  It says `Expected ":"` because the next character after the valid identifier name `memory_in_` the parser expected a ":" rather than a "G".  Not sure how to fix this.

**Comment by dimitri-yatsenko** [comment]
Perhaps at least we could print the string that caused the error.  The error message correctly indicated the position in the string that cause the error.

**Comment by eywalker** [comment]
Yes, let's print out the offending line during parsing. I think based on how we parse, it can narrow down completely to the problematic line.

**Comment by vmr160030** [comment]
For anyone else who stumbles on this like I did, the problem is with capital letters in attribute names. The [docs](https://docs.datajoint.org/python/definition/04-Definition-Syntax.html#attribute-names) specify valid attribute names:

> Attribute names must be in lowercase and must start with a letter. They can only contain alphanumerical characters and underscores. The attribute name cannot exceed 64 characters.
> 
> Valid attribute names
> `first_name`, `two_photon_scan`, `scan_2p`, `two_photon_scan_`
> 
> Invalid attribute names
> `firstName`, `first name`, `2photon_scan`, `two-photon_scan`, `TwoPhotonScan`
