### ISSUE TITLE
Issue with delete() method

### ISSUE THREAD

**Issue by meet10may** [datajoint/datajoint-python#444]
Hi,
I was following the tutorial for "building the first pipeline" and while deleting the entries, I encountered this error message...I am using datajoint 0.10.0
Any suggestions where am I making the mistake?

mouse.delete()
Traceback (most recent call last):

File "<ipython-input-212-05abbadb20db>", line 1, in <module>
  mouse.delete()

File "/home/tanmay/anaconda3/lib/python3.6/site-packages/datajoint-0.10.0-py3.6.egg/datajoint/base_relation.py", line 316, in delete
  for table in graph.descendants(self.full_table_name):

File "/home/tanmay/anaconda3/lib/python3.6/site-packages/datajoint-0.10.0-py3.6.egg/datajoint/dependencies.py", line 104, in descendants
  return [full_table_name] + nx.algorithms.dag.topological_sort(self, nodes)

TypeError: topological_sort() takes 1 positional argument but 2 were given
Thanks

**Comment by ixcat** [comment]
Hello - can you provide the output of ```pip list``? This looks like an issue possibly related to having version 2 of networkx (a dependency package) installed.

**Comment by meet10may** [comment]
yes, you are right...I have 2 versions of networkx installed..

I removed the 2.0 and kept only 1.11. Then it seems to work. Thanks for the support.
