### ISSUE TITLE
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column

### ISSUE THREAD

**Issue by reezalaq** [datajoint/datajoint-python#473]
I'm trying to insert data via request but keep getting this error  : 

## server.py ##
class Users(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(80))
    license_key = db.Column(db.String(50), unique=True)
    expiration_date = db.Column(db.String(50), unique=True)
    woocommerce_details = db.relationship('Woocommerce', backref='users', lazy='joined')
    aliexpress_details = db.relationship('AliExpress', backref='aliusers', lazy='joined')
    overview_details = db.relationship('Overview', backref='overviewusers', lazy='joined')

class Woocommerce(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    woocommerceUrl = db.Column(db.String(100), nullable=False)
    woocommerceConsumer = db.Column(db.String(100), nullable=False)
    woocommerceSecret = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

class AliExpress(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    api_key = db.Column(db.Integer)
    affiliateid = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

class Overview(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    productid = db.Column(db.String(100), nullable=True)
    producttitle = db.Column(db.String(100), nullable=True)
    producturl = db.Column(db.String(100), nullable=True)
    imageurl = db.Column(db.String(100), nullable=True)
    originalprice = db.Column(db.String(100), nullable=True)
    saleprice = db.Column(db.String(100), nullable=True)
    evaluatescore = db.Column(db.String(100), nullable=True)
    buyurl = db.Column(db.String(100), nullable=True)
    date = db.Column(db.String(100), nullable=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

class TodoSimple2(Resource):
    def put(self, username, productid, date, producttitle, buyurl, imageurl, saleprice):
        user = Users.query.filter_by(username=username).first()
        print(user)
        if user:
            element = Overview(user_id=user.id, productid=productid, date=date, producttitle=producttitle, buyurl=buyurl, imageurl=imageurl, saleprice=saleprice)
            print(element)
            db.session.add(element)
            db.session.commit()
            return {"status": "OK"}
        else:
            return {"status": "ERROR", "error": "user doesn't exist"}

api.add_resource(TodoSimple2, '/api/v1/<string:username>/<string:productid>/<string:date>/<string:producttitle>/<string:buyurl>/<string:imageurl>/<string:saleprice>')

## test3.py ##

import requests
username = "reezalaq"
productid = "12345"
date = "2018.07.13"
producttitle = "test product title"
buyurl = "sometext"
imageurl = "sometext"
saleprice = "12.34"
r = requests.put('http://localhost:5000/api/v1/'+ username + "/" + productid + "/" + date + "/" + producttitle + "/" + buyurl + "/" + imageurl + "/" + saleprice )

print(r.content)

## error message ## : 

Traceback (most recent call last):
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/reezalaq/PycharmProjects/wooexpress/server.py", line 173, in put
    user = Users.query.filter_by(username=username).first()
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/reezalaq/venv/wooexpress/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'overview_1.saleprice' in 'field list'") [SQL: 'SELECT anon_1.users_id AS anon_1_users_id, anon_1.users_username AS anon_1_users_username, anon_1.users_email AS anon_1_users_email, anon_1.users_password AS anon_1_users_password, anon_1.users_license_key AS anon_1_users_license_key, anon_1.users_expiration_date AS anon_1_users_expiration_date, woocommerce_1.id AS woocommerce_1_id, woocommerce_1.`woocommerceUrl` AS `woocommerce_1_woocommerceUrl`, woocommerce_1.`woocommerceConsumer` AS `woocommerce_1_woocommerceConsumer`, woocommerce_1.`woocommerceSecret` AS `woocommerce_1_woocommerceSecret`, woocommerce_1.user_id AS woocommerce_1_user_id, ali_express_1.id AS ali_express_1_id, ali_express_1.api_key AS ali_express_1_api_key, ali_express_1.affiliateid AS ali_express_1_affiliateid, ali_express_1.user_id AS ali_express_1_user_id, overview_1.id AS overview_1_id, overview_1.productid AS overview_1_productid, overview_1.producttitle AS overview_1_producttitle, overview_1.producturl AS overview_1_producturl, overview_1.imageurl AS overview_1_imageurl, overview_1.originalprice AS overview_1_originalprice, overview_1.saleprice AS overview_1_saleprice, overview_1.evaluatescore AS overview_1_evaluatescore, overview_1.buyurl AS overview_1_buyurl, overview_1.date AS overview_1_date, overview_1.user_id AS overview_1_user_id \nFROM (SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.password AS users_password, users.license_key AS users_license_key, users.expiration_date AS users_expiration_date \nFROM users \nWHERE users.username = %(username_1)s \n LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN woocommerce AS woocommerce_1 ON anon_1.users_id = woocommerce_1.user_id LEFT OUTER JOIN ali_express AS ali_express_1 ON anon_1.users_id = ali_express_1.user_id LEFT OUTER JOIN overview AS overview_1 ON anon_1.users_id = overview_1.user_id'] [parameters: {'username_1': 'reezalaq', 'param_1': 1}]

**Comment by eywalker** [comment]
Hey @reezalaq two things:
* When you post code snippet, please insert them into an appropriate code block so that it's properly formatted and syntax highlighted - otherwise it's really difficult to read what you posted.
* I don't see how this is related to DataJoint package - did you mean to post this to SQLAlchemy?

**Comment by eywalker** [comment]
I'm closing this issue as this does not seem to be related to DataJoint. I'd be happy to reopen if it turns out otherwise.
