### ISSUE TITLE
using .proj to generate attributes does not (fully?) support non-string types

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#606]
Using `.proj()` to generate attributes does not seem to work for (at least) integers; This could be fairly handy... (possibly related to #587)

nok:
```
>> Table.proj(bogus=0)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/chris/src/djc/datajoint-python/datajoint/expression.py", line 251, in proj
    return Projection.create(self, attributes, named_attributes)
  File "/Users/chris/src/djc/datajoint-python/datajoint/expression.py", line 733, in create
    attributes, named_attributes = Projection.prepare_attribute_lists(arg, attributes, named_attributes)
  File "/Users/chris/src/djc/datajoint-python/datajoint/expression.py", line 709, in prepare_attribute_lists
    named_attributes = {k: v.strip() for k, v in named_attributes.items()}  # clean up
  File "/Users/chris/src/djc/datajoint-python/datajoint/expression.py", line 709, in <dictcomp>
    named_attributes = {k: v.strip() for k, v in named_attributes.items()}  # clean up
AttributeError: 'int' object has no attribute 'strip'
```
ok:
```
>>> Table.proj(bogus='"0"')
*subject_uuid  *session_start bogus    
+------------+ +------------+ +-------+
00c60db3-74c3- 2019-02-21 00: 0        
00c60db3-74c3- 2019-02-21 17: 0        
00c60db3-74c3- 2019-03-08 18: 0        
00c60db3-74c3- 2019-03-09 15: 0        
00c60db3-74c3- 2019-03-11 16: 0        
00c60db3-74c3- 2019-03-12 16: 0        
00c60db3-74c3- 2019-03-13 19: 0        
   ...
 (Total: 4573)
```

**Comment by dimitri-yatsenko** [comment]
But `.proj(bogus="0")` will produce the correct result, right?

**Comment by dimitri-yatsenko** [comment]
Just had a quick discussion with Chris and we decided that the current implementation is complete and consistent and we need to clarify the documentation on supplying constant literals in `proj` computations. The proj computation is always supplied as a string. Inside the string, values are specified either as string or numbers. 

```python
Table.proj(bogus="0")  # number
Table.proj(bogus="'0'")  # string 
```
Will add to documentation shortly.

**Comment by dimitri-yatsenko** [comment]
I am adding this to the documentation and closing.
