### ISSUE TITLE
Bug in fetching with `order_by` specified on attributes that are not part of the returned attribute list

### ISSUE THREAD

**Issue by ttngu207** [datajoint/datajoint-python#914]
### Description
DataJoint encountered error in fetching with `order_by` specified on attributes that are not part of the returned attribute list. (error stack pasted below)

This line yields the error stack below:

```
scan.ScanInfo.Field.fetch('KEY', order_by='field_z')
```

It seems like fetching just the 'KEY' part does the projection before the ordering, so order_by=field_z couldn't find field_z.
Fetch everything works just fine:

```
scan.ScanInfo.Field.fetch(order_by='field_z')
```

Error stack:
```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-118-2c9725558855>", line 1, in <module>
    scan.ScanInfo.Field.fetch('KEY', order_by='field_z')
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\datajoint\fetch.py", line 182, in __call__
    format='array')
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\datajoint\fetch.py", line 193, in __call__
    as_dict=as_dict, limit=limit, offset=offset, order_by=order_by)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\datajoint\expression.py", line 519, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\datajoint\connection.py", line 302, in query
    self._execute_query(cursor, query, args, suppress_warnings)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\datajoint\connection.py", line 268, in _execute_query
    raise translate_query_error(err, query)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\datajoint\connection.py", line 266, in _execute_query
    cursor.execute(query, args)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\ProgramData\Miniconda3\envs\workflow-imaging\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (3065, "Expression #1 of ORDER BY clause is not in SELECT list, references column 'neuro_imaging._scan_info__field.field_z' which is not in SELECT list; this is incompatible with DISTINCT")
```

### Reproducibility
Include:
- OS (WIN)
- Python Version 3.7
- MySQL Version 5.7
- MySQL Deployment Strategy (local-native)
- DataJoint Version (0.13.1)

**Comment by dimitri-yatsenko** [comment]
Apparently, with `DISTINCT` in the SELECT statement, the `ORDER BY` clause cannot use attributes not included in the select when the `ONLY_FULL_GROUP_BY` setting is on. https://bugs.mysql.com/bug.php?id=81342

**Comment by dimitri-yatsenko** [comment]
The solution to this will be to eliminate `DISTINCT` when it is not necessary.

**Comment by ttngu207** [comment]
> Has this been solved already?

@horsto , this is not yet solved. I'm using the working around like this:

```
keys, _ = scan.ScanInfo.Field.fetch('KEY', 'field_z', order_by='field_z')
```

(quite inefficient, fetching and discarding `field_z`, but works)
