### ISSUE TITLE
dj.ERD(schema).save() FileNotFoundError: "dot" not found in path.

### ISSUE THREAD

**Issue by Yambottle** [datajoint/datajoint-python#924]
### Description
I was trying to save an ERD into a svg image, and then got this error: `FileNotFoundError: [Errno 2] "dot" not found in path.`
It seems like the `pydot` is not compatible with macOS, I haven't test it in other environment yet.

### Reproducibility
Include:
- OS: macOS 11.1
- Python 3.6.13 with conda 4.9.2
- MySQL Version: using `tutorial-db.datajoint.io`
- MySQL Deployment Strategy remote
- DataJoint 0.13.2
- Minimum number of steps to reliably reproduce the issue
```
def plot_erd(tpath:str):
    """
    Plot ERD and save it at current work directory
    
    :param tpath: target path
    """
    schema = dj.Schema(dj.config['schema'])
    dj.ERD(schema).save(os.path.join(tpath, 'ERD.svg'), format='svg') # Error
```
- Complete error stack as a result of evaluating the above steps
```
Traceback (most recent call last):
  File "./pipeline/run.py", line 137, in <module>
    main(args)
  File "./pipeline/run.py", line 118, in main
    plot_erd(tpath)
  File "./pipeline/run.py", line 34, in plot_erd
    dj.ERD(schema).save(os.path.join(tpath, 'ERD.svg'), format='svg')
  File "/Users/yam/opt/anaconda3/envs/datajoint/lib/python3.6/site-packages/datajoint/diagram.py", line 347, in save
    f.write(self.make_svg().data)
  File "/Users/yam/opt/anaconda3/envs/datajoint/lib/python3.6/site-packages/datajoint/diagram.py", line 314, in make_svg
    return SVG(self.make_dot().create_svg())
  File "/Users/yam/opt/anaconda3/envs/datajoint/lib/python3.6/site-packages/pydot.py", line 1734, in new_method
    format=f, prog=prog, encoding=encoding)
  File "/Users/yam/opt/anaconda3/envs/datajoint/lib/python3.6/site-packages/pydot.py", line 1933, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.
```

---

### Additional Research and Context
Add any additional research or context that was conducted in creating this report.

For example:
- Related GitHub issues and PR's either within this repository or in other relevant repositories.
- Specific links to specific lines or a focus within source code.
- Relevant summary of Maintainers development meetings, milestones, projects, etc.

**Comment by Yambottle** [comment]
> Hi @Yambottle -
> 
> The ERD/Diagram support requires that the 'graphviz' package be installed on your system, and that the binaries it provides (such as `dot`) can be found in the executable search path. ($PATH on Unix-like systems)
> 
> For MacOS, instructions can be found here: https://graphviz.org/download/#mac
> 
> Reviewing the documentation, it seems that aside from windows, this is under-documented - will close this issue and open another one presenting this as a documentation problem.
> 
> In the meantime, feel free to me on the datajoint slack if you have any setup questions.

Make sense to me! Thanks for your support!
