### ISSUE TITLE
populate() throws an error if schema.list_tables() is called before a computed table's definition and not recalled afterwards

### ISSUE THREAD

**Issue by A-Baji** [datajoint/datajoint-python#988]
### Description
Calling `schema.list_tables()` at any point before a computed table's definition, and then calling the computed table's `populate()` method without calling `schema.list_tables()` again beforehand throws a DataJoint error.

### Reproducibility
- Linux
- Python 3
- DataJoint 0.13.2
- Steps:
  1. Create an manual or lookup table
  2. Call `schema.list_tables()`
  3. Create a computed table using the previous table as a foreign key
  4. Call the computed table's `populate()`
```
print(schema.list_tables()) 

@schema
class Subject(dj.Lookup):
    definition = """
    subject_id: int
    """
    contents = [dict(subject_id=1)] 

@schema
class Session(dj.Computed):
    definition = """
    -> Subject
    time: varchar(30)
    """
    
    def make(self, key):
        new_entry = dict(**key, time=datetime.now())
        self.insert1(new_entry)
    
Session.populate()
```
- Complete error stack as a result of evaluating the above steps:
```
Traceback (most recent call last):
  File "/home/.anaconda/test.py", line 29, in <module>
    Session.populate() # invokes Session's make(), passing Subject's primary key
  File "/opt/conda/lib/python3.9/site-packages/datajoint/autopopulate.py", line 128, in populate
    keys = (self._jobs_to_do(restrictions) - self.target).fetch("KEY", limit=limit)
  File "/opt/conda/lib/python3.9/site-packages/datajoint/autopopulate.py", line 80, in _jobs_to_do
    todo = self.key_source
  File "/opt/conda/lib/python3.9/site-packages/datajoint/autopopulate.py", line 42, in key_source
    raise DataJointError(
datajoint.errors.DataJointError: A relation must have primary dependencies for auto-populate to work
```

### Expected Behavior
The computed table's `populate()` should successfully run its `make()` function, passing the foreign key's values as the `key` parameter.

### Screenshots
**[doesn't work]** Calling `schema.list_tables` only _before_ the computed table's definition:
![image](https://user-images.githubusercontent.com/61991709/151632746-4ff9b668-01c9-4c38-b963-7e7677644f15.png)

**[works]** Calling `schema.list_tables` only _after_ the computed table's definition:
![image](https://user-images.githubusercontent.com/61991709/151633162-30e28cbb-4b4e-4358-bf48-a8351fb94228.png)

**[works]** Calling `schema.list_tables` _before and after_ the computed table's definition:
![image](https://user-images.githubusercontent.com/61991709/151633233-150eee2a-17d8-4046-9847-a8d1d523268a.png)

**Comment by dimitri-yatsenko** [comment]
This is fixed in DataJoint 2.0.

**Root cause:** In older versions, the dependencies cache wasn't properly reloaded when `populate()` was called after new tables were declared.

**Fix:** `Dependencies.parents()` now calls `self.load(force=False)` before returning results:

```python
def parents(self, table_name, primary=None):
    self.load(force=False)  # Ensures dependencies are current
    return {...}
```

**How it works now:**
1. `list_tables()` → loads dependencies, sets `_loaded = True`
2. New table declared via `@schema` → calls `dependencies.clear()`, sets `_loaded = False`
3. `populate()` → calls `parents()` → calls `load(force=False)` → reloads from database since `_loaded = False`

The dependencies cache is now properly invalidated when tables are declared and lazily reloaded when needed.
